version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    environment:
      - NODE_ENV=production
    networks:
      - gsk-kvartal-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - nextjs
    networks:
      - gsk-kvartal-network
    restart: unless-stopped
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro # <--- добавьте эту строку

networks:
  gsk-kvartal-network:
    driver: bridge
