version: '3.8'

services:
  nextjs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs
    image: hubulbib/gsk-kvartal-nextjs:latest
    environment:
      - NODE_ENV=production
    volumes:
      # - .:/app
      - /app/node_modules
    networks:
      - gsk-kvartal-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    image: hubulbib/gsk-kvartal-nginx:latest
    ports:
      - '80:80'
    depends_on:
      - nextjs
    networks:
      - gsk-kvartal-network
    restart: unless-stopped

networks:
  gsk-kvartal-network:
    driver: bridge
